config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: "restaurants#index"
  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  validates :name, presence: true, format: {with: /\A[A-Z]/}
  validates :cuisine, presence: true, length: { minimum: 3 }

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating) # some kind of rails magic. lol
    # reviews.inject(0) { |sum, review| sum + review.rating } / reviews.count.to_f
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :restaurant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :authenticate_user!, except: [:index]

  def index
    @restaurants = Restaurant.all
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render :new
    end 
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]
    @restaurant.update restaurant_params
    redirect_to '/restaurants'
  end

  # def destroy
  #   @restaurant = Restaurant.find(params[:id])
  #   @restaurant.destroy
  #   flash[:notice] = "Successfully deleted #{@restaurant.name}"
  #   redirect_to '/restaurants'
  # end

  def destroy
    @restaurant = current_user.restaurant.find params[:id]
    @restaurant.destroy
    flash[:notice] = "Successfully deleted #{@restaurant.name}"
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Not your restaurant!"
  ensure
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = @restaurant.reviews.create params[:review].permit(:thoughts, :rating)
    redirect_to '/restaurants' unless request.xhr?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    # return rating if rating.is_a?(String)
    rounded_rating = rating.round
    remainder = (5 - rounded_rating)
    ('★' * rounded_rating) + ('☆' * remainder)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <!-- <%= notice %>
  <%= alert %> -->
  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   
      <%= link_to('Edit Details', edit_user_registration_path) %>     
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
      <%= link_to('Sign Up', new_user_registration_path)  %>  
    </li>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <div id='error-list'>
  <h2>Errors</h2>
  <ul>
  <% @restaurant.errors.full_messages.each do |error| %>
  <li> <%= error %> </li>
<% end %>
</ul>
  </div>
<% end %>

<%= form_for @restaurant do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine, required: true %>

  <%= f.submit %>
  
<% end %> 

app/views/restaurants/edit.html.erb
<h1>Update a Restaurant</h1>

<%= render 'form'%>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <ul>
  <% @restaurants.each do |restaurant| %>
    <li class='restaurant'><%= restaurant.name %> (<%= restaurant.cuisine %>) 
      Average rating: 
      <span class='average_rating'>
        <%= star_rating(restaurant.average_rating) %>
      </span>  <br>
      <% if user_signed_in? %>
      <%= link_to "Edit", edit_restaurant_path(restaurant.id) %>
      <%= link_to "Delete", restaurant_path(restaurant.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to "Review", new_restaurant_review_path(restaurant.id) %>
        <% end %> 
      <ul class='reviews'>
        <% restaurant.reviews.each do |review| %>
          <li><%= review.thoughts %> (<%= star_rating review.rating %>)</li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <%= form_for [restaurant, @review] do |f| %>
        <%= f.label :thoughts %>
        <%= f.text_area :thoughts %>
        <%= f.label :rating %>
        <%= f.select :rating, 1..5 %>
        <%= f.submit %>
      <% end %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>
<%= link_to 'Create Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create a New Restaurant</h1>

<%= render 'form'%>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>

  <%= f.label :rating %>
  <%= f.select :rating, 1..5 %>

  <%= f.submit %>
<% end %>